version: '3.8'
services:
  postgres:
    image: postgres:17.3
    container_name: my-postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: realworld_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
